import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/header";

const notoSans = Noto_Sans({
    variable: "--font-noto-sans", // лучше дать осмысленное имя CSS-переменной
    subsets: ["latin", "cyrillic"],
    weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={' scroll-smooth'} style={{scrollbehavior: "smooth"}} lang="en">
        <body
            className={`${notoSans.variable} font-sans bg-black text-white/60 antialiased scroll-smooth`}
        >
        <Header />
        {children}
        </body>
        </html>
    );
}